[package]
name = "crs"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
owo-colors = { version = "3.3.0", features = ["supports-colors"] }
